# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'LivingRoom' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    
    #响应式函数框架
    pod 'RxSwift', '~> 4.3.1'
    
    #响应式函数框架
    pod 'RxCocoa', '~> 4.3.1'
    
    #布局框架
    pod 'SnapKit', '~> 4.0.0'
    
    #网络层
    pod 'Moya', '~> 11.0.0'
    
    #网络层扩展
    pod 'Moya/RxSwift', '~> 11.0'
    
    #图片下载框架
    pod 'Kingfisher', '~> 4.6.1'
    
    #ORM框架
    pod 'HandyJSON'
    
    #基础框架
    pod 'Base', :git => 'https://github.com/dearmiku/MN_Live_Base.git'
    
    # Pods for LivingRoom
    
end
